# Config for NeverLoseYourSphere

# Available languages: en, ru
language: en

additional-messages:
- "&7There is no need to place that."
- "&7It's better to keep it in your inventory."
#- "&7Лучше не надо это ставить..."
#- "&7Эту штуку лучше оставить в инвентаре."
